sonar.projectKey=raiakarsh_Spendsmart-backend
sonar.organization=raiakarsh
sonar.projectName=Spendsmart Backend
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8
sonar.java.source=21
sonar.scm.disabled=true

sonar.sources=auth-service/src/main/java,expense-service/src/main/java,income-service/src/main/java,category-service/src/main/java,budget-service/src/main/java,recurring-service/src/main/java,analytics-service/src/main/java,notification-service/src/main/java,gateway-service/src/main/java,eureka-server/src/main/java
sonar.tests=auth-service/src/test/java,expense-service/src/test/java,income-service/src/test/java,category-service/src/test/java,budget-service/src/test/java,recurring-service/src/test/java,analytics-service/src/test/java,notification-service/src/test/java
sonar.test.inclusions=**/src/test/java/**/*.java
sonar.exclusions=**/target/**,**/.idea/**,**/*.md,**/*.pdf,**/*.json

sonar.java.binaries=auth-service/target/classes,expense-service/target/classes,income-service/target/classes,category-service/target/classes,budget-service/target/classes,recurring-service/target/classes,analytics-service/target/classes,notification-service/target/classes,gateway-service/target/classes,eureka-server/target/classes
sonar.java.test.binaries=auth-service/target/test-classes,expense-service/target/test-classes,income-service/target/test-classes,category-service/target/test-classes,budget-service/target/test-classes,recurring-service/target/test-classes,analytics-service/target/test-classes,notification-service/target/test-classes
sonar.coverage.jacoco.xmlReportPaths=auth-service/target/site/jacoco/jacoco.xml,expense-service/target/site/jacoco/jacoco.xml,income-service/target/site/jacoco/jacoco.xml,category-service/target/site/jacoco/jacoco.xml,budget-service/target/site/jacoco/jacoco.xml,recurring-service/target/site/jacoco/jacoco.xml,analytics-service/target/site/jacoco/jacoco.xml,notification-service/target/site/jacoco/jacoco.xml,gateway-service/target/site/jacoco/jacoco.xml,eureka-server/target/site/jacoco/jacoco.xml
