# ================================================================
#  income-service   -  Port 8083
#  Handles: add/edit/delete income, filter by source, totals
# ================================================================

server.port=8083
spring.application.name=income-service

# Eureka Service Discovery
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# CHANGE THIS: use your MySQL password
spring.datasource.url=jdbc:mysql://localhost:3306/spendsmart_income?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT  -  MUST match auth-service's jwt.secret exactly
jwt.secret=SpendSmartSecretKey2026_Standard32Bytes!

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true

